### ISSUE TITLE
Better management of stored journal data 

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/jv2#229]
Following merge of #225, better management of journal data is required. Rather than storing journal data in a specified directory structure, we can simply maintain and write the JournalLibrary to a given local file.

This will allow us to cache any retrieved journal data from network sources as well as maintain generated journal data.

## TODO
- [x] Move `Journal`s into their associated `JournalSource` since they are tightly associated with that object.
- [x] Clarify purpose of `rootUrl` variable for `JournalSource` - this is _only_ valid for network sources in reality.
- [x] Rename enumerations for type (e.g. now `Network` and `Cache`) since that's what we're currently handling.
- [x] #221
- [x] ~Need to check our cache for journal indices in `get_index()`~
- [x] Move `Instrument`, or at least `currentInstrument_` into `JournalSource` since it is tightly associated to the `JournalSource` in some sense.
